// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260309223033_FixNomenclaturePrice")]
    partial class FixNomenclaturePrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("device_types", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("nomenclatures", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Country.CountryCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(2)")
                                .HasColumnName("Code");

                            b1.HasKey("CountryId");

                            b1.ToTable("countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Country.CountryName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(70)")
                                .HasColumnName("Name");

                            b1.HasKey("CountryId");

                            b1.ToTable("countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DeviceType", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Handbook.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("DeviceTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(511)")
                                .HasColumnName("Description");

                            b1.HasKey("DeviceTypeId");

                            b1.ToTable("device_types");

                            b1.WithOwner()
                                .HasForeignKey("DeviceTypeId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Handbook.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(70)")
                                .HasColumnName("Name");

                            b1.HasKey("DeviceTypeId");

                            b1.ToTable("device_types");

                            b1.WithOwner()
                                .HasForeignKey("DeviceTypeId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Manufacturer", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Handbook.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ManufacturerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(511)")
                                .HasColumnName("Description");

                            b1.HasKey("ManufacturerId");

                            b1.ToTable("manufacturers");

                            b1.WithOwner()
                                .HasForeignKey("ManufacturerId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Handbook.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ManufacturerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(70)")
                                .HasColumnName("Name");

                            b1.HasKey("ManufacturerId");

                            b1.ToTable("manufacturers");

                            b1.WithOwner()
                                .HasForeignKey("ManufacturerId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Nomenclature", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Nomenclature.DeviceImage", "DeviceImage", b1 =>
                        {
                            b1.Property<Guid>("NomenclatureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Caption")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Caption");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Url");

                            b1.HasKey("NomenclatureId");

                            b1.ToTable("nomenclatures");

                            b1.WithOwner()
                                .HasForeignKey("NomenclatureId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Nomenclature.ModelName", "ModelName", b1 =>
                        {
                            b1.Property<Guid>("NomenclatureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("ModelName");

                            b1.HasKey("NomenclatureId");

                            b1.ToTable("nomenclatures");

                            b1.WithOwner()
                                .HasForeignKey("NomenclatureId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Nomenclature.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("NomenclatureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("NomenclatureId");

                            b1.ToTable("nomenclatures");

                            b1.WithOwner()
                                .HasForeignKey("NomenclatureId");
                        });

                    b.Navigation("Country");

                    b.Navigation("DeviceImage")
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("Manufacturer");

                    b.Navigation("ModelName")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
